### ISSUE TITLE
Melhorar a descrição do seu README

### ISSUE THREAD

**Issue by vcwild** [Chrigor/AutenticacaoJWT#1]
Boa noite, verifiquei que esse projeto é bem interessante, mas está faltando informar mais como ele funciona e qual a finalidade dele no seu README.md.

Caso esteja em dúvida do que colocar em um README, deixo aqui minha sugestão:
[O que colocar em um arquivo README](https://www.embarcados.com.br/o-que-escrever-num-readme/)

Caso tenha dificuldade com arquivos markdown, aqui tem um tutorial muito simples e direto:
[Markdown syntax](https://www.markdownguide.org/basic-syntax/)

**Comment by Chrigor** [comment]
@vcwild muito obrigado! amanhã cedo vou dar uma olhada e adicionar o README.md aqui! 😁
